site_name: Machine Learning Foundations

theme:
    name: material
    logo: assets/images/logo.png
    features:
        #- navigation.tabs
        - header.autohide
        - navigation.indexes
nav:
  - Home: index.md
  - Contribute: contribute.md
  - Linear Algebra:
    - linear_algebra/0-linear_algebra.md
    - linear_algebra/1-ml_problem.md
    - linear_algebra/2-linear_model.md
    - linear_algebra/3-system_1.md
    - linear_algebra/4-system_2.md
    - linear_algebra/5-least_squares.md
    - linear_algebra/6-best_fit.md
    - linear_algebra/7-projections.md
    - linear_algebra/8-eigenvalues.md
  - Appendix:
    - appendix/0-gradients.md
    - appendix/1-cauchy_schwarz.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - def_list
  - attr_list
  - md_in_html
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

