site_name: Machine Learning Foundations

theme:
    name: material
    logo: assets/images/logo.png
    features:
        #- navigation.tabs
        - header.autohide
        - navigation.indexes
nav:
  - Home: index.md
  - Week-1:
    - week-1/density_estimation.md
  - Week-2:
    - None
  - Week-3:
    - week-3/outline.md
    - week-3/0-linear_algebra.md
    - week-3/1-ml_problem.md
    - week-3/2-linear_model.md
    - week-3/3-system_1.md
    - week-3/4-system_2.md
    - week-3/5-least_squares.md
    - week-3/6-best_fit.md
    - week-3/7-projections.md
  - Week-4:
    - week-4/outline.md
    - week-4/transformations.md
    - week-4/eigenvectors.md
    - week-4/char_polynomial.md
  - Appendix:
    - appendix/0-gradients.md
    - appendix/1-cauchy_schwarz.md
  - Contribute: contribute.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      css_style:
        width: "100%"

